/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/Appoiments': RouteRecordInfo<'/Appoiments', '/Appoiments', Record<never, never>, Record<never, never>>,
    '/IncompleteVaccines': RouteRecordInfo<'/IncompleteVaccines', '/IncompleteVaccines', Record<never, never>, Record<never, never>>,
    '/MonthlyCostByPet': RouteRecordInfo<'/MonthlyCostByPet', '/MonthlyCostByPet', Record<never, never>, Record<never, never>>,
    '/Owners': RouteRecordInfo<'/Owners', '/Owners', Record<never, never>, Record<never, never>>,
    '/Pets': RouteRecordInfo<'/Pets', '/Pets', Record<never, never>, Record<never, never>>,
    '/Treatments': RouteRecordInfo<'/Treatments', '/Treatments', Record<never, never>, Record<never, never>>,
    '/UpcomingAppointments': RouteRecordInfo<'/UpcomingAppointments', '/UpcomingAppointments', Record<never, never>, Record<never, never>>,
    '/Vaccine': RouteRecordInfo<'/Vaccine', '/Vaccine', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/Appoiments.vue': {
      routes: '/Appoiments'
      views: never
    }
    'src/pages/IncompleteVaccines.vue': {
      routes: '/IncompleteVaccines'
      views: never
    }
    'src/pages/MonthlyCostByPet.vue': {
      routes: '/MonthlyCostByPet'
      views: never
    }
    'src/pages/Owners.vue': {
      routes: '/Owners'
      views: never
    }
    'src/pages/Pets.vue': {
      routes: '/Pets'
      views: never
    }
    'src/pages/Treatments.vue': {
      routes: '/Treatments'
      views: never
    }
    'src/pages/UpcomingAppointments.vue': {
      routes: '/UpcomingAppointments'
      views: never
    }
    'src/pages/Vaccine.vue': {
      routes: '/Vaccine'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
